# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "7d7c1f35-8b6a-43bd-9b4d-87733cc9cce2"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  cocoapods

  increment_version_number(
    bump_type: "patch"
)

  commit_version_bump

  # build your iOS app
  gym(
    scheme: "KomicaViewer",
    workspace: "KomicaViewer.xcworkspace",
    clean: true,
    export_method: "app-store"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
