source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brion/OGVKit-Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

workspace 'KomicaViewer.xcworkspace'
xcodeproj 'KomicaViewer.xcodeproj'
xcodeproj '../../komicaengine/KomicaEngine.xcodeproj'


target 'KomicaViewer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks    
  use_frameworks!
  
  xcodeproj 'KomicaViewer.xcworkspace'
  
  # Pods for KomicaViewer
  pod "MWPhotoBrowser", '~> 2.1.2'
  pod "MBProgressHUD"
  pod "AFNetworking"
  pod "PureLayout"
  pod 'SVPullToRefresh', :git => 'https://github.com/samvermette/SVPullToRefresh.git'
  pod 'SVWebViewController', :git => 'https://github.com/TransitApp/SVWebViewController.git'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Crash'
  pod "OGVKit"
  pod 'SwiftMessages'
  target 'KomicaViewerTests' do
   inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
