source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'KomicaViewer' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KomicaViewer
  pod 'SDWebImage', '~>3.8'
  pod "MWPhotoBrowser"
  pod 'MBProgressHUD', '~> 1.0.0'
  target 'KomicaViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
